### ISSUE TITLE
Can anyone help or explain this to me ?

### ISSUE THREAD

**Issue by Yusuprozimemet** [entbappy/Chicken-Disease-Classification--Project#2]
On the notebook, everything runs smoothly, and I generated a final training model. However, when I run it on Git Bash, I encounter this issue.

$ python main.py
2024-06-21 00:54:08.726134: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-21 00:54:10.954988: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-06-21 00:54:16,015: INFO: utils: NumExpr defaulting to 4 threads.]
[2024-06-21 00:54:17,725: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-21 00:54:17,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-21 00:54:17,734: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-21 00:54:17,735: INFO: common: created directory at: artifacts]
[2024-06-21 00:54:17,735: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-21 00:54:17,736: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2024-06-21 00:54:18,133: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-21 00:54:18,133: INFO: main: *******************]
[2024-06-21 00:54:18,133: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-21 00:54:18,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-21 00:54:18,140: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-21 00:54:18,141: INFO: common: created directory at: artifacts]
[2024-06-21 00:54:18,142: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-21 00:54:19,072: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
Model: "functional_1"
+--------------------------------------------------------------------------+
| Layer (type)                    | Output Shape           |       Param # |
|---------------------------------+------------------------+---------------|
| input_layer (InputLayer)        | (None, 224, 224, 3)    |             0 |
|---------------------------------+------------------------+---------------|
| block1_conv1 (Conv2D)           | (None, 224, 224, 64)   |         1,792 |
|---------------------------------+------------------------+---------------|
| block1_conv2 (Conv2D)           | (None, 224, 224, 64)   |        36,928 |
|---------------------------------+------------------------+---------------|
| block1_pool (MaxPooling2D)      | (None, 112, 112, 64)   |             0 |
|---------------------------------+------------------------+---------------|
| block2_conv1 (Conv2D)           | (None, 112, 112, 128)  |        73,856 |
|---------------------------------+------------------------+---------------|
| block2_conv2 (Conv2D)           | (None, 112, 112, 128)  |       147,584 |
|---------------------------------+------------------------+---------------|
| block2_pool (MaxPooling2D)      | (None, 56, 56, 128)    |             0 |
|---------------------------------+------------------------+---------------|
| block3_conv1 (Conv2D)           | (None, 56, 56, 256)    |       295,168 |
|---------------------------------+------------------------+---------------|
| block3_conv2 (Conv2D)           | (None, 56, 56, 256)    |       590,080 |
|---------------------------------+------------------------+---------------|
| block3_conv3 (Conv2D)           | (None, 56, 56, 256)    |       590,080 |
|---------------------------------+------------------------+---------------|
| block3_pool (MaxPooling2D)      | (None, 28, 28, 256)    |             0 |
|---------------------------------+------------------------+---------------|
| block4_conv1 (Conv2D)           | (None, 28, 28, 512)    |     1,180,160 |
|---------------------------------+------------------------+---------------|
| block4_conv2 (Conv2D)           | (None, 28, 28, 512)    |     2,359,808 |
|---------------------------------+------------------------+---------------|
| block4_conv3 (Conv2D)           | (None, 28, 28, 512)    |     2,359,808 |
|---------------------------------+------------------------+---------------|
| block4_pool (MaxPooling2D)      | (None, 14, 14, 512)    |             0 |
|---------------------------------+------------------------+---------------|
| block5_conv1 (Conv2D)           | (None, 14, 14, 512)    |     2,359,808 |
|---------------------------------+------------------------+---------------|
| block5_conv2 (Conv2D)           | (None, 14, 14, 512)    |     2,359,808 |
|---------------------------------+------------------------+---------------|
| block5_conv3 (Conv2D)           | (None, 14, 14, 512)    |     2,359,808 |
|---------------------------------+------------------------+---------------|
| block5_pool (MaxPooling2D)      | (None, 7, 7, 512)      |             0 |
|---------------------------------+------------------------+---------------|
| flatten (Flatten)               | (None, 25088)          |             0 |
|---------------------------------+------------------------+---------------|
| dense (Dense)                   | (None, 2)              |        50,178 |
+--------------------------------------------------------------------------+
 Total params: 14,764,866 (56.32 MB)
 Trainable params: 50,178 (196.01 KB)
 Non-trainable params: 14,714,688 (56.13 MB)
[2024-06-21 00:54:19,315: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-21 00:54:19,440: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-21 00:54:19,440: INFO: main: *******************]
[2024-06-21 00:54:19,440: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-06-21 00:54:19,444: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-21 00:54:19,446: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-21 00:54:19,446: INFO: common: created directory at: artifacts]
[2024-06-21 00:54:19,446: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2024-06-21 00:54:19,447: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2024-06-21 00:54:19,447: ERROR: main: The filepath provided must end in `.keras` (Keras model format). Received: filepath=artifacts\prepare_callbacks\checkpoint_dir\model.h5]
Traceback (most recent call last):
  File "E:\Chicken_Disease_Classification_Project\main.py", line 34, in <module>
    model_trainer.main()
  File "e:\chicken_disease_classification_project\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\chicken_disease_classification_project\src\cnnClassifier\components\prepare_callbacks.py", line 37, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "e:\chicken_disease_classification_project\src\cnnClassifier\components\prepare_callbacks.py", line 28, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\keras\src\callbacks\model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=artifacts\prepare_callbacks\checkpoint_dir\model.h5
Traceback (most recent call last):
  File "E:\Chicken_Disease_Classification_Project\main.py", line 38, in <module>
    raise e
  File "E:\Chicken_Disease_Classification_Project\main.py", line 34, in <module>
    model_trainer.main()
  File "e:\chicken_disease_classification_project\src\cnnClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\chicken_disease_classification_project\src\cnnClassifier\components\prepare_callbacks.py", line 37, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "e:\chicken_disease_classification_project\src\cnnClassifier\components\prepare_callbacks.py", line 28, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\keras\src\callbacks\model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=artifacts\prepare_callbacks\checkpoint_dir\model.h5

**Comment by Yusuprozimemet** [comment]
I fixed the problems by myself. The latest version of TensorFlow does not support Python 3.8, so I made TensorFlow and Python compatible (Python == 3.10.12, TensorFlow == 2.15). There were also some errors in the code in training.py, which I fixed. Now it works well.
![Screenshot (2237)](https://github.com/entbappy/Chicken-Disease-Classification--Project/assets/82045682/71eef3be-aa55-4248-b6da-a30a819b1354)
